# ---------------------------------------------------------
# 1. Le Déploiement
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: spring-boot-app
          image: taoufykmed/demo-app:1.0
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: hello-world-storage
              mountPath: /app/data
      volumes:
        - name: hello-world-storage
          persistentVolumeClaim:
            claimName: pvc-hello-world

---

# ---------------------------------------------------------
# 2. Le Service (Gère l'accès réseau vers les Pods)
# ---------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

# ---------------------------------------------------------
# 3. Pod volume
# ---------------------------------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hello-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


